#!/bin/sh

usage() {
	cat <<EOF 1>&2
Usage: $0 [-i <inputdir>] [-o <outputdir>] [-r] [-- ocroptions]"
Automatically OCRmyPDF files in input directory and put the result into
output directory. Specify the options for OCRmyPDF after the double
hyphen (--).

Arguments:
	   -i: Input directory
	   -o: Output directory
	   -r: Remove input file on successful conversion
EOF
		  exit 1;
		}

INPUTDIR=/input
OUTPUTDIR=/output
REMOVEONSUCCESS=true

while getopts ":i:o:hr" o; do
	case "${o}" in
		i)
			INPUTDIR="${OPTARG}"
			;;
		o)
			OUTPUTDIR="${OPTARG}"
			;;
		r)
			REMOVEONSUCCESS=rm
			;;
		h)
			usage
			;;
	esac
done
shift $((OPTIND-1))

OCRMYPDFOPTS="$*"

outfilename() {
	OUTFILE="$1"
	if [ -e "$OUTFILE" ]; then
		name="${1%.*}"
		ext="${1##*.}"
		NUM=$(ls "$name"* | wc -l)
		OUTFILE="$name".$NUM.$ext
	fi
}

convert_infile()
{
	outfilename "$OUTPUTDIR/$1"

	ocrmypdf $OCRMYPDFOPTS "$INPUTDIR/$F" "$OUTFILE" && $REMOVEONSUCCESS "$INPUTDIR/$F"
}

inotifywait -m -e CLOSE_WRITE -q "$INPUTDIR" --format %f |
	while read F; do
		  convert_infile $F
	done
