# OCRmyPDF
#
# VERSION               4.4.2
FROM      jbarlow83/ocrmypdf:latest
MAINTAINER James R. Barlow <jim@purplerock.ca>

USER root

RUN add-apt-repository ppa:alex-p/tesseract-ocr

RUN apt-get update && apt-get install -y --no-install-recommends \
	tesseract-ocr-all

RUN apt-get autoremove -y && apt-get clean -y

USER docker


# Must use array form of ENTRYPOINT
# Non-array form does not append other arguments, because that is "intuitive"
ENTRYPOINT ["/application/docker-wrapper.sh"]
