#!/bin/sh

########################################################################
# JHOVE - JSTOR/Harvard Object Validation Environment
# Copyright 2003-2005 by JSTOR and the President and Fellows of Harvard College
# JHOVE is made available under the GNU General Public License (see the
# file LICENSE for details)
#
# Usage: jhove [-c config] [-m module] [-h handler] [-e encoding] [-H handler]
#              [-o output] [-x saxclass] [-t tempdir] [-b bufsize]
#              [-l loglevel] [[-krs] dir-file-or-uri [...]]
#
# where -c config   Configuration file pathname
#       -m module   Module name
#       -h handler  Output handler name (defaults to TEXT)
#       -e encoding Character encoding of output handler (defaults to UTF-8)
#       -H handler  About handler name
#       -o output   Output file pathname (defaults to standard output)
#       -x saxclass SAX parser class (defaults to J2SE 1.4 default)
#       -t tempdir  Temporary directory in which to create temporary files
#       -b bufsize  Buffer size for buffered I/O (defaults to J2SE 1.4 default)
#       -k          Calculate CRC32, MD5, and SHA-1 checksums
#       -r          Display raw data flags, not textual equivalents
#       -s          Format identification based on internal signatures only
#       dir-file-or-uri Directory, file pathname or URI of formatted content
#
# CHANGE for JHOVE 1.8:
# You no longer have to figure out where JAVA_HOME is; that's the
# operating system's job. If the OS tells you it can't find Java, 
# adjust your shell's path or revert to the old way (commented out).
# Configuration constants:

#JHOVE_HOME=/users/gary/dev/jhove
JHOVE_HOME=[fill in path to jhove directory]

JAVA_HOME=/usr/java      # Java JRE directory -- change to your local java home
JAVA=$JAVA_HOME/bin/java # Java interpreter -- usually won't need change

#XTRA_JARS=/users/stephen/xercesImpl.jar
EXTRA_JARS=              # Extra .jar files to add to CLASSPATH

# NOTE: Nothing below this line should be edited
########################################################################

CP=${JHOVE_HOME}/bin/JhoveApp.jar:${EXTRA_JARS}

# Retrieve a copy of all command line arguments to pass to the application.

ARGS=""
for ARG do
    ARGS="$ARGS $ARG"
done

# Set the CLASSPATH and invoke the Java loader.
#{JAVA} -classpath $CP Jhove $ARGS -x org.apache.xerces.parsers.SAXParser
#${JAVA} -classpath $CP Jhove $ARGS
# New way, doesn't require you to use JAVA_HOME.
java -classpath $CP Jhove $ARGS