#!/bin/sh

########################################################################
# userhome - JSTOR/Harvard Object Validation Environment
# Copyright 2004-2006 by the President and Fellows of Harvard College
# JHOVE is made available under the GNU General Public License (see the
# file LICENSE for details)
#
# Driver script to display the default Java user.home property
#
# Usage: userhome
#
# Configuration constants:

JHOVE_HOME=/users/stephen/projects/jhove

JAVA_HOME=/usr/java      # Java JRE directory
JAVA=$JAVA_HOME/bin/java # Java interpreter

# NOTE: Nothing below this line should be edited
########################################################################

# Set the CLASSPATH and invoke the Java loader.
${JAVA} -classpath ${JHOVE_HOME}/classes UserHome
