/* Generated By:JavaCC: Do not edit this line. ParseHtmlConstants.java */
package edu.harvard.hul.ois.jhove.module.html;

public interface ParseHtmlConstants {

  int EOF = 0;
  int STARTDOCTYPE = 1;
  int LABRACKET = 2;
  int PCDATASTART = 3;
  int PCDATA = 4;
  int NAME = 5;
  int EQUALS = 6;
  int NAKEDVALUE = 7;
  int QUOTEDVALUE = 8;
  int SINGQUOTEDVALUE = 9;
  int QMARK = 10;
  int SLASH = 11;
  int COLON = 12;
  int RABRACKET = 13;
  int DOCTYPEKEYWORD = 14;
  int NAKEDDTITEM = 15;
  int QUOTEDDTITEM = 16;
  int OPENCOMMENT = 22;

  int DEFAULT = 0;
  int IN_PCDATA = 1;
  int IN_TAG = 2;
  int IN_ATTVALUE = 3;
  int IN_DOCTYPE = 4;
  int IN_DOCTYPE2 = 5;
  int IN_COMMENT = 6;
  int ENDING_COMMENT = 7;

  String[] tokenImage = {
    "<EOF>",
    "\"<!\"",
    "\"<\"",
    "<PCDATASTART>",
    "<PCDATA>",
    "<NAME>",
    "<EQUALS>",
    "<NAKEDVALUE>",
    "<QUOTEDVALUE>",
    "<SINGQUOTEDVALUE>",
    "\"?\"",
    "\"/\"",
    "\":\"",
    "\">\"",
    "\"DOCTYPE\"",
    "<NAKEDDTITEM>",
    "<QUOTEDDTITEM>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<!--\"",
    "\"--\"",
    "<token of kind 24>",
    "\">\"",
    "<token of kind 26>",
  };

}
