#!/bin/sh

########################################################################
# j2dump - JSTOR/Harvard Object Validation Environment
# Copyright 2004-2005 by the President and Fellows of Harvard College
# JHOVE is made available under the GNU General Public License (see the
# file LICENSE for details)
#
# Driver script for the JPEG 2000 dump utility
#
# Usage: j2dump file
#
# where  file  is a JPEG file
#
# Configuration constants:

JHOVE_HOME=/users/stephen/projects/jhove

JAVA_HOME=/usr/java      # Java JRE directory
JAVA=$JAVA_HOME/bin/java # Java interpreter

EXTRA_JARS=              # Extra .jar files to add to CLASSPATH

# NOTE: Nothing below this line should be edited
########################################################################

CP=${JHOVE_HOME}/bin/JhoveApp.jar:${EXTRA_JARS}

# Retrieve a copy of all command line arguments to pass to the application.

ARGS=""
for ARG do
    ARGS="$ARGS $ARG"
done

# Set the CLASSPATH and invoke the Java loader.
${JAVA} -classpath $CP J2Dump $ARGS
